name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run type-check && npm run lint && npm run format
